### ISSUE TITLE
Fatal error at last step of Compiling ORDU project

### ISSUE THREAD

**Issue by naughtod** [ghlkm/ordu#1]
Hi,

I've followed all of your nice detailed instructions but unfortunately I get a fatal error at the final step!

Under heading, "To Compile this project, ORDU", I run this step,
`cmake --build .  # it may should a lot of warnings because I set "-Wall" in CMakelists.txt`

The error message I get is,
![image](https://user-images.githubusercontent.com/57878980/180591968-76e10ac2-f4a7-4b81-ae71-b5b0453b05c9.png)

However, the file that is not found is actually just in a different folder.

![image](https://user-images.githubusercontent.com/57878980/180591412-4a09458c-4dd2-4f50-92b0-f68c2a19ea9e.png)

Since it won't compile I can't run the algorithm. Is there any way to fix this? I have tried changing the #include reference in "RboxPoints.h" and it fixes this but then another similar issue pops up. Seems that all the #include references are pointing to the wrong place which makes me think there might be something wrong with the install steps for qhull.

FYI using MacOS Monterey v12.4.

Thanks,
David

**Comment by ghlkm** [comment]
> Hi,
> 
> I've followed all of your nice detailed instructions but unfortunately I get a fatal error at the final step!
> 
> Under heading, "To Compile this project, ORDU", I run this step, `cmake --build . # it may should a lot of warnings because I set "-Wall" in CMakelists.txt`
> 
> The error message I get is, ![image](https://user-images.githubusercontent.com/57878980/180591968-76e10ac2-f4a7-4b81-ae71-b5b0453b05c9.png)
> 
> However, the file that is not found is actually just in a different folder.
> 
> ![image](https://user-images.githubusercontent.com/57878980/180591412-4a09458c-4dd2-4f50-92b0-f68c2a19ea9e.png)
> 
> Since it won't compile I can't run the algorithm. Is there any way to fix this? I have tried changing the #include reference in "RboxPoints.h" and it fixes this but then another similar issue pops up. Seems that all the #include references are pointing to the wrong place which makes me think there might be something wrong with the install steps for qhull.
> 
> FYI using MacOS Monterey v12.4.
> 
> Thanks, David


Have you ever obey the step install the qhull lib and check " /usr/local/include" whether contains all the corresponding headers?

`sudo cmake --build . --target install # check /usr/local/lib contains libqhull relavent lib and whether /usr/local/include contains libqhull relavent hearders.`

**Comment by ghlkm** [comment]
I think you might miss the step or something wrong happen in installing qhull 
"sudo cmake --build . --target install".

You can have a check in "/usr/local/include" to see if you have corresponding missing files.

**Comment by naughtod** [comment]
Thanks, you were right. 

I just needed to update the CMakeLists.txt to add, 
`include_directories(/usr/local/include)`

I now have another issue, error message is,
<img width="977" alt="image" src="https://user-images.githubusercontent.com/57878980/180650432-1bbd57f9-55f6-4870-ad59-457e2f0fde2d.png">

The issue seems to be the red black tree iterator `_Rb_tree_iterator` is not defined for me. I think it should be in C++ STL so i'm not sure why it isn't there. Would it be due to the version of C++ CMake is using?

Thanks,
David

**Comment by ghlkm** [comment]
"_Rb_tree_iterator" should be part of std lib of c++.

I think in the CMakeLists.txt， I have try to make C++ version as C++14, and CMake version as 3.10 at least. But I didn't control what is the gcc version. It might be such that your gcc version is too old.

Except update your gcc version, you could also simply change " _Rb_tree_iterator<pair<const RADIUS, NODE_PTR>>" into "auto", which might uses "__tree_iterator" in your mac,  but it might run slower than using "_Rb_tree_iterator".

**Comment by naughtod** [comment]
Thanks i'll try that. I found this [https://stackoverflow.com/questions/70319413/how-use-libstdc-instead-libc-macos-12-0](url) which says that libstdc++ is not shipped or supported with macOs so I would need to try and download it if you're suggestion fails.

**Comment by naughtod** [comment]
auto worked

**Comment by naughtod** [comment]
It looks good (got to 100%) but for some reason I got a linker error right at the end,
<img width="563" alt="image" src="https://user-images.githubusercontent.com/57878980/180653069-4d81e3fb-40da-451d-b29c-e4700249c16e.png">

**Comment by ghlkm** [comment]
It says it can not reconize flag "--no-as-needed", which I found it happen in macOS sometimes

Try change CMakeLists.txt line 26

"set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wl,--no-as-needed -O3 -Wall -ldl")"

into 

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -Wall -ldl")

**Comment by naughtod** [comment]
thanks, this fixed it. Everything running as expected now. 

Thanks for your help, I will close this issue now.
